name: Nightly

on:
  push:
    branches: [ "main" ]


jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install libarchive
      run: sudo apt update && sudo apt install libarchive-dev
    - name: Install zig
      run: wget https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz && tar -xvf zig-linux-x86_64-0.13.0.tar.xz
    - name: Compile
      run: ./zig-linux-x86_64-0.13.0/zig build -Doptimize=ReleaseFast -Dcpu=baseline
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        draft: false
        prerelease: false
        tag_name: nightly-${{ github.sha }}
        name: Nightly Build ${GITHUB_SHA::7}
        files: |
          ./zig-out/bin/zigdemu
          ./zig-out/bin/zigd
